# ~/.config/starship.toml

# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’æŒ¿å…¥ã—ã¾ã™ã€‚
add_newline = true

# ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ã‚¹ã‚­ãƒ£ãƒ³ã™ã‚‹éš›ã®ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 10

# è¨˜å·ã®è¨­å®š
[character]
success_symbol = "[\\( Â´ â–½ ` \\)ï¾‰](bold white)" # ã‚³ãƒžãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[\\(ã€‚>ã…¿<ã€‚\\)](bold white)"    # ã‚³ãƒžãƒ³ãƒ‰å¤±æ•—æ™‚

# condaç’°å¢ƒã®è¡¨ç¤º
[conda]
format = "[$symbol$environment](dimmed green) "
ignore_base = false  # baseç’°å¢ƒã‚‚è¡¨ç¤ºã•ã›ãŸã„

# AWS
[aws]
format = '[(on $symbol $profile)]($style)'

# Git
[git_branch]
symbol = "ðŸŒ± "
